issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - tagliatelle
        - dupl
        - exhaustivestruct
        - gci
        - gofumpt
        - funlen
        - varnamelen
        - containedctx
        - maintidx
linters:
  enable-all: true
  disable:
    - tagliatelle
    - dupl
    - exhaustivestruct
    - gci
    - gofumpt
    - nonamedreturns
    - exhaustruct
    - nolintlint
    - depguard
